# Generated by Django 4.0.4 on 2022-04-20 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_tag_options_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['is_done', '-datetime']},
        ),
    ]
